include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generate/**/*.dart"
    - "scripts/*.dart"
    - "test/*.dart"
    - "lib/oss_licenses.dart"
  errors:
    invalid_annotation_target: ignore
    depend_on_referenced_packages: ignore