name: mypoly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  flutter_lints: ^5.0.0

  # CLI
  melos: ^7.3.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

melos:
  useRootAsPackage: true

  scripts:
    clean:
      steps:
        - fvm flutter clean
        - fvm flutter pub get
        - |
          if [[ "$OSTYPE" == "darwin"* ]]; then
            fvm flutter precache --ios
          fi