name: mypoly
description: "MyPOLY"
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # State
  hooks_riverpod: ^3.1.0
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^4.0.0

  # API
  retrofit: ^4.7.3
  dio: ^5.9.0

  # Model
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Route
  auto_route: ^11.1.0

  # Widget
  flutter_screenutil: ^5.9.3
  loader_overlay: ^5.0.0
  skeletonizer: ^2.1.2
  flutter_svg: ^2.2.3
  cached_network_image: ^3.4.1

  # Native
  flutter_native_splash: ^2.4.7

  # Util
  collection: ^1.19.1
  keyboard_detection: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Runner
  build_runner: ^2.10.5

  # Route
  auto_route_generator: ^10.4.0

  # State
  riverpod_generator: ^4.0.0+1

  # API
  retrofit_generator: ^10.0.0

  # Model
  freezed: ^3.2.3
  json_serializable: ^6.11.1

  # Lint
  flutter_lints: ^6.0.0
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0

  # CLI
  melos: ^7.3.0
  spider: ^4.2.3
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  openapi_generator_cli: ^6.1.0
  dotenv: ^4.2.0

flutter:
  config:
    enable-swift-package-manager: false

  uses-material-design: true

  assets:
    - .env
    - .env.dev
    - assets/svg/
    - assets/webp/
    
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/font/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Pretendard-Light.ttf
          weight: 300
        - asset: assets/font/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/font/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/font/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/font/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/font/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Pretendard-Black.ttf
          weight: 900
    
melos:
  useRootAsPackage: true

  scripts:
    clean:
      steps:
        - fvm flutter clean
        - fvm flutter pub get
        - test "$(uname)" = "Darwin" && fvm flutter precache --ios && cd ios && pod install && cd .. || true
        - fvm flutter pub run spider build
        - fvm flutter pub run build_runner build --delete-conflicting-outputs

    watch:
      steps:
        - fvm flutter pub run build_runner watch --delete-conflicting-outputs

    spider:
      steps:
        - fvm flutter pub run spider build --watch

    gen:
      steps:
        - fvm dart run scripts/generate_openapi.dart